#db.url=${DB_URL}
#db.username=${DB_USERNAME}
#db.password=${DB_PASSWORD}
#db.driverClassName=org.postgresql.Driver

db.url=jdbc:postgresql://localhost:5432/employee_payroll_db
db.username=postgres
db.password=Az@12345678
db.driverClassName=org.postgresql.Driver